### ISSUE TITLE
Show something in "My Rules" even when none exist yet

### ISSUE THREAD

**Issue by spacegaier** [stanford-oval/almond-hassio-repository#8]
Not sure if something should be in that panel, but apart from a "My Rules" header there is nothing if no rules were created yet. Is that expected behaviour for the current version?

If there are no rules yet, perhaps a short text indicating so with a hint on how to create them might be helpful. Otherwise users might think something failed to render (as I did at first 😄).

EDIT: Now that I think about it, this is probably the wrong repo as the Almond GUI is most likely not specific to that HA add-on.

**Comment by gcampax** [comment]
Fixed by https://github.com/stanford-oval/almond-server/pull/198
